---
## change ip dhcp helper addr on SVI's and subinterface's 
# doesn't work on ME3400 and won't work on older L2 switches
# they don't support commad: sh run | sec interface for gathering facts
#
- hosts: cmp_routers
  gather_facts: false
  connection: network_cli
  tasks:

#  - name: whoami
#    debug:
#      var: ansible_user
#
  - name: get ios facts min
    ios_facts:
      gather_subset: min

      # - debug: var=ansible_net_version
  - debug: 
      msg:
        - "{{ansible_net_model}}"
        - "{{ansible_net_version}}"

  - fail: 
      msg: "platform not suitable"
    when: ( (ansible_net_model is regex("(?i)ME-3400")) or (ansible_net_model is regex("(?i)Nexus")) )
   

  - name: get ios facts L3 int
    ios_facts:
      gather_network_resources: l3_interfaces

  - name: change helper address
    ios_config:
      lines:
        - no ip helper-address
        - ip helper-address 192.168.10.248
      parents: "interface {{item.key}}"
    loop: "{{ansible_net_interfaces | dict2items}}"
    when: ((item.value.ipv4.0.address is defined) and (item.value.ipv4.0.address is regex("192.168.") ) and (item.key is not regex("Loopback") ))

     


  - name: save config
    ios_config:
      save_when: changed

      
#  - name: enum l3 int
#    debug:
#      msg:
#        - "{{item.key}}"
#        - "{{item.value.ipv4.0.address}}"
#    loop: "{{ansible_net_interfaces | dict2items}}"
#    when: ((item.value.ipv4.0.address is defined) and (item.value.ipv4.0.address is regex("192.168.") ) and (item.key is not regex("Loopback") ))

