---
- hosts: pagi-ssh-dev
  gather_facts: false
  connection: network_cli
  # limit no of targets a time 
  serial: 10
  tasks:

    # ios_user
  - name: set authentication
    ios_config:
      lines:
        - username irekk privilege 15 secret 5 $1$NOHk$/465WGpRY3ceCWrPXEv.l.
        - username pagi privilege 15 secret 5 $1$GaxY$v2PaFp4VA7MPGnVk88N37/
        - aaa new-model


  - name : set archive
    ios_config:
      parents: archive
      lines:
        - path tftp://212.69.68.123/$h-@-$t
        - write-memory


  - name: set acls 10
    ios_config:
      before: no access-list 10
      lines:
        - access-list 10 permit 212.69.66.0 0.0.0.63
        - access-list 10 permit 212.69.68.123


  - name: security off vty lines
    ios_config:
      parents: line vty 0 4
      lines:
        - no access-class 1 in
        - no access-class login in

  - name: set acls 1
    ios_config:
      before: no access-list 1
      lines:
        - access-list 1 permit 212.69.66.0 0.0.0.31
        - access-list 1 permit 212.69.68.123


  - name: security on vty lines
    ios_config:
      parents: line vty 0 4
      lines:
        - exec-timeout 60
        - logging synchronous
        - access-class 1 in vrf-also
        - transport input ssh

          
  - name: security on con line
    ios_config:
      parents: line con 0
      lines:
        - exec-timeout 240
        - logging synchronous


  - name: ssh tune
    ios_config:
      lines:
        - ip ssh time-out 60
        - ip ssh authentication-retries 5
        - ip scp server enable


  - name: set timestamps
    ios_config:
      lines:
        - service timestamps debug datetime msec localtime show-timezone year
        - service timestamps log datetime msec localtime show-timezone year


  - name: set timezone
    ios_config:
      lines:
        - clock timezone CET 1 0
        - clock summer-time CEST recurring last Sun Mar 2:00 last Sun Oct 3:00

  - name: set ntp1
    ios_ntp:
      server: 212.69.81.115
      logging: false
      state: present
  #  register: ntpserv
  #- debug: var=ntpserv

  - name: set ntp2
    ios_ntp:
      server: 212.69.68.123
      logging: false
      state: present
  #  register: ntpserv2
  #- debug: var=ntpserv2

  - name: set ntp srv prefer
    ios_config:
      lines:
        - ntp server 212.69.81.115 prefer
        - no ntp logging
 



  - name: save config
    ios_config:
      save_when: always
