---
  # customer name : cmp
  # set ACL on vty lines, secure dev access
  #
- hosts: cmp
  gather_facts: false
  connection: network_cli
  tasks:

  - name: get ios facts
    ios_facts:
      gather_subset: 
          - min

#  - debug:
#      msg: 
#        - "{{ansible_net_model}}"
#        - "{{inventory_hostname}}"
#   
  - fail:
      msg: not for nexus platform
    when: ansible_net_model is regex("(?i)Nexus")



  - name: rm access-class from vty lines
    when: inventory_hostname is regex("(?i)cmp")
    ignore_errors: True
    ios_config:
      parents: line vty 0 4
      lines:
        - no access-class clogin in vrf-also

   
  # ACL order of the entries and remarks tends to be unpredictable; adding numbers before permit doesn't help - probably gets optimized by CEF
  - name: set ACL clogin standard
    when: inventory_hostname is regex("(?i)cmp")
    cisco.ios.ios_config:
      parents: ip access-list standard clogin
      lines:
        - remark **Helpdesk, nagiosAWS, loc mgmt**
        - permit 212.69.66.0 0.0.0.63
        - permit host 212.69.68.123
        - permit host 52.210.128.8
        - permit host 192.168.10.34
        - permit host 192.168.10.235
        - permit 10.0.0.0 0.0.0.255
      match: exact
      replace: block


  - name: ins access-class on vty lines 
    ignore_errors: True
    ios_config:
      parents: line vty 0 4
      lines:
        - access-class clogin in vrf-also


  - name: save config
    ios_config:
      save_when: changed


