---
  # customer name : cmp
  # set ACL on vty lines, secure dev access
  #
- hosts: cmp
  gather_facts: false
  connection: network_cli
  tasks:

  - name: get ios facts
    ios_facts:
      gather_subset: 
          - min

#  - debug:
#      msg: 
#        - "{{ansible_net_model}}"
#        - "{{inventory_hostname}}"
#   
  - fail:
      msg: not for nexus platform
    when: ansible_net_model is regex("(?i)Nexus")



  - name: rm access-class from vty lines
    when: inventory_hostname is regex("(?i)cmp")
    ignore_errors: True
    ios_config:
      parents: line vty 0 4
      lines:
        - no access-class clogin in vrf-also


  # first fetch the ACL from a device, then modify 
  # https://www.ansible.com/blog/deep-dive-acl-configuration-management-using-ansible-network-automation-resource-modules
  #
  # state: overriden = overwrite any manual changes
  #
  # ? bug with afi:
  # FAILED! => {"changed": false, "msg": "Unsupported parameters for (ios_acls) module: acls, afi Supported parameters include: config, running_config, state"}
  # but https://docs.ansible.com/ansible/2.10/collections/cisco/ios/ios_acls_module.html says: ipv4, ipv6
  - name: set ACL to secure vty lines
    ignore_errors: True
    ios_acls:
      state: overridden
      config:
        - afi: ipv4
          acls:
            - name: clogin
              acl_type: standard
              aces: 
              -   grant: permit
                  sequence: 10
                  source:
                      address: 192.168.10.34
              -   grant: permit
                  sequence: 20
                  source:
                      address: 52.210.128.8
              -   grant: permit
                  sequence: 50
                  source:
                      address: 192.168.10.235
              -   grant: permit
                  sequence: 30
                  source:
                      address: 212.69.68.123
              -   grant: permit
                  sequence: 40
                  source:
                      address: 212.69.66.0
                      wildcard_bits: 0.0.0.63
              -   grant: permit
                  sequence: 60
                  source:
                      address: 10.0.0.0
                      wildcard_bits: 0.0.0.255
    tags: setacl


  - name: ins access-class on vty lines 
    ignore_errors: True
    ios_config:
      parents: line vty 0 4
      lines:
        - access-class clogin in vrf-also


  - name: save config
    ios_config:
      save_when: changed


