# ansible-playbook -vvv sh_ver.yml
---
- hosts: ztm-wkm-sw1
#- hosts: LINX-RT10-cASR1002-2
#- hosts: ZTM-WKM-RT1_inet_L0
#- hosts: pagi-ssh-dev
  gather_facts: false
  connection: network_cli
  serial: 10
  tasks:
    - name : get ios_facts
      ios_facts:
        gather_subset: interfaces
      register: int

    - debug:
        msg:
          - "{{item.key}}"
      loop: "{{ansible_facts.ansible_net_interfaces | dict2items}}"
      when: item.key is not regex("show") and item.key is not regex("%") 
      #and item.value.lineprotocol is not regex("None") and item.value.operstatus is not regex("deleted")
    

    - name: list interfaces
      debug:
        msg: 
          - "int_name:: {{item.key}}"
          - "operstatus: {{item.value.operstatus}} ; line proto: {{item.value.lineprotocol}}"
      loop: "{{int.ansible_facts.ansible_net_interfaces | dict2items}}"
      when: item.value.operstatus is not regex("deleted")

