---
- name: convert configured ACLs to structured data
  hosts: cmp_routers
  gather_facts: false
  tasks:

    - fail:
      when: inventory_dir is undefined


      #- debug: var=inventory_dir

      # on ios 12.4 fails with: An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not iterable

    - name: Use the ACLs resource module to gather the current config
      cisco.ios.ios_acls:
        state: gathered
      register: acls

    - name: Create inventory directory
      file:
        path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}"
        state: directory

    - name: Write the ACL configuration to a file
      copy:
        content: "{{ {'acls': acls['gathered']} | to_nice_yaml }}"
        dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/acls.yaml"
