---
- hosts: pagi-ssh-dev
  gather_facts: false
  connection: network_cli
  # limit no of targets a time 
  serial: 10
  tasks:

  - name: set acls 10
    ignore_errors: True
    ios_config:
      #before: no access-list 10
      #parents: access-list 10
      lines:
        - access-list 10 permit 212.69.66.0 0.0.0.63
        - access-list 10 permit 212.69.68.123


  - name: security off vty lines
    ios_config:
      parents: line vty 0 4
      lines:
        - no access-class 1 in

  - name: set acls 1
    ignore_errors: True
    ios_config:
      #before: no access-list 1
      #parents: access-list 1
      lines:
        - access-list 1 permit 212.69.66.0 0.0.0.31
        - access-list 1  permit 212.69.68.123


  - name: security on vty lines
    ios_config:
      parents: line vty 0 4
      lines:
        - exec-timeout 60
        - logging synchronous
        - access-class 1 in vrf-also
        - transport input ssh

          

  - name: save config
    ios_config:
      save_when: always
